import {loadTimeData} from '//resources/js/load_time_data.js';
loadTimeData.data = {
    "addSuggestionToSpeedDial": "Add to Speed Dial",
    "addToOperaButton": "Add to Opera",
    "addToOperaInputPlaceholder": "Type address to add to your Speed Dial",
    "addToOperaSuggestions": "Suggestions",
    "addToOperaTitle": "Add to Opera",
    "addressBarDropdownCities": false,
    "addressbarYandexBox": false,
    "bookmarksContextMenuDontShowAgain": "Don't show again",
    "branch-value": "Early Access",
    "campaignsMenuDontShowAgain": "Don't show again",
    "campaignsMenuRemindTomorrow": "Remind me tomorrow",
    "cancel_button": "Cancel",
    "cashback": true,
    "cashbackWidgetFlagEnabled": false,
    "channel-name": "stable",
    "closeLabel": "Close",
    "colorThemeEnabled": false,
    "componentUI": true,
    "contentContextCopyLinkLocation": "Copy link addr&ess",
    "contextMenuChangeTheme": "Change wallpaper",
    "contextMenuConfigureLiveWallpaper": "Configure live wallpaper",
    "contextMenuDelete": "Remove",
    "contextMenuDontShowAgain": "Don't show again",
    "contextMenuEdit": "Edit",
    "contextMenuMoveToTrash": "Move to Trash",
    "contextMenuOpenFolderInNewTab": "Open all in new tabs",
    "contextMenuOpenFolderInNewWindow": "Open all in new window",
    "contextMenuOpenFolderInPrivateWindow": "Open all in new private window",
    "contextMenuOpenFolderInWorkspace": "Open all in &workspace",
    "contextMenuOpenInNewPrivateWindow": "Open in new private window",
    "contextMenuOpenInNewTab": "Open in new tab",
    "contextMenuOpenInNewWindow": "Open in new window",
    "contextMenuOpenInWorkspace": "Open in &workspace",
    "contextMenuRemoveCustomImage": "Remove custom image",
    "contextMenuSetCustomImage": "Set custom image",
    "continueBookingMenuDiscardAll": "Clear all Booking.com items",
    "continueBookingSectionName": "Continue on Booking.com",
    "continueItem": "1 item",
    "continueItems": "$1 items",
    "continueMenuDoNotShow": "Don't show again",
    "continueMenuRemindTomorrow": "Remind me tomorrow",
    "continueNewItem": "1 new item",
    "continueNewItems": "$1 new items",
    "continueOnBooking": true,
    "continueShopping": true,
    "continueShoppingExplore": false,
    "continueShoppingExploreHide": "Hide",
    "continueShoppingExploreMore": "More",
    "continueShoppingExploreNoResultsCaption": "No results found",
    "continueShoppingExploreSponsoredDisclaimer": "Sponsored",
    "continueShoppingFeedbackRatingAverage": "Could be better",
    "continueShoppingFeedbackRatingBad": "Not at all",
    "continueShoppingFeedbackRatingGood": "It's cool",
    "continueShoppingHideExplore": "Hide Explore option",
    "continueShoppingMenuDiscardAll": "Discard all items",
    "continueShoppingSectionName": "Continue shopping",
    "continueShoppingShowExplore": "Show Explore option",
    "dailyWallapersOnboardingAcceptButton": "Got it",
    "dailyWallapersOnboardingConfigure": "Configure",
    "dailyWallapersOnboardingLabel": "Hey! The new feature “Daily Wallpaper” is now enabled.",
    "dailyWallapersSkipWallpaperHint": "Skip this wallpaper",
    "defaultFolderName": "Folder",
    "delete": "Delete",
    "done": "Done",
    "easySetupFullStats": false,
    "easyShareAppUrl": "https://flow.opera.com/ext/v1/start-gx",
    "edit": "Edit",
    "editAddressLabel": "Address",
    "editNameLabel": "Name",
    "featureFeedbackCancelButton": "Not now",
    "featureFeedbackCommentsPlaceholder": "Tell us more (your opinion matters)",
    "featureFeedbackHeader": "How useful is this feature?",
    "featureFeedbackSubmitButton": "Send",
    "featureFeedbackTitle": "Your opinion",
    "folder_names": {
        "_imported_from_opera_link_": "Imported From Opera Link",
        "_reading_list_": "Reading list",
        "_shopping_": "Shopping",
        "_travel_": "Travel",
        "_videos_": "Videos"
    },
    "fontfamily": "'Segoe UI', Tahoma, sans-serif",
    "fontfamilyMd": "'Segoe UI', Tahoma, sans-serif",
    "fontsize": "75%",
    "gxChromaSettingsDuplicateSet": "Duplicate",
    "gxChromaSettingsDuplicatedSetName": "Duplicate of $1",
    "gxChromaSettingsExport": "Export",
    "gxCornerCMSEnabled": true,
    "gxDailyWallpapersFeatureEnabled": false,
    "gxGameStripsAddLabel": "Add Game Strip",
    "gxGameStripsEnabled": true,
    "gxGameStripsLabel": "Game strips",
    "gxPanicButton": true,
    "gxPostMortemCleanup": true,
    "gxReactinator": true,
    "gxShadersExceptions": false,
    "gxSpotlightNewTheme": "New theme",
    "gxSpotlightUnlockMod": "Unlock",
    "gxSpotlightUnlockingMod": "Unlocking…",
    "gxUi2024": true,
    "gxWidgetsAutohidePanel": "Always hide panel",
    "gxWidgetsGamesEnabled": true,
    "gxWidgetsGamesLabel": "Show GX Games",
    "gxWidgetsGxMeEditLabel": "Edit profile",
    "gxWidgetsGxMeLabel": "Show GX.me",
    "gxWidgetsHackerViewLabel": "Show Hacker view",
    "gxWidgetsLinksLabel": "Show Links",
    "gxWidgetsLogoutLabel": "Log out",
    "gxWidgetsMissionCheckReward": "Check your reward",
    "gxWidgetsMissionClaim": "Claim",
    "gxWidgetsMissionComplete": "Mission complete",
    "gxWidgetsMissionDone": "Done!",
    "gxWidgetsMissionEnabled": false,
    "gxWidgetsMissionLabel": "Show Mission",
    "gxWidgetsMissionLikeIt": "Did you like it?",
    "gxWidgetsMissionRewardCountdown": "Run Opera GX tomorrow, to receive a reward $1 left.",
    "gxWidgetsMissionRewardHeader": "You've claimed",
    "gxWidgetsMissionRewardName": "Soulsborne mod",
    "gxWidgetsMissionRewardTip": "Mod can be changed in the $1",
    "gxWidgetsMissionRewardUnlockTip": "Complete this mission to receive the $1",
    "gxWidgetsMissionRewardUnlocked": "Reward unlocked!",
    "gxWidgetsMissionUnlock": "Unlock an Exclusive Mod!",
    "gxWidgetsMobileModsLabel": "Show Mobile Mods",
    "gxWidgetsMobileModsPopupHeader": "Get Opera GX Mobile",
    "gxWidgetsMobileModsPopupText": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "gxWidgetsMobileModsScanQrCode": "Scan QR code to download Opera GX on your mobile",
    "gxWidgetsMobileModsText": "Welcome GX Mods in Opera GX Mobile!",
    "gxWidgetsMobileModsTryIt": "Try it",
    "gxWidgetsModsEnabled": true,
    "gxWidgetsModsLabel": "Show GX Mods",
    "gxWidgetsNewLookFeedback": "Let us know",
    "gxWidgetsNewLookLabel": "Show New Look",
    "gxWidgetsNewLookReasonPlaceholder": "Because…",
    "gxWidgetsNewLookRestartRequired": "Relaunch and try the new GX",
    "gxWidgetsNewLookRollbackConfirm": "Revert and relaunch",
    "gxWidgetsNewLookRollbackTitle": "Why are you rolling back?",
    "gxWidgetsNewLookTitle": "Like the new GX?",
    "gxWidgetsNewLookTitleComing": "See what's coming",
    "gxWidgetsNewLookTryIt": "Try the new GX",
    "gxWidgetsSignUpLabel": "Sign up",
    "gxWidgetsTitle": "Widgets",
    "gxWidgetsWeatherLabel": "Show Weather",
    "isGX": true,
    "isGX2024": true,
    "isPrivateWindow": false,
    "labelCancel": "Cancel",
    "labelOk": "OK",
    "language": "en",
    "liveBackground": true,
    "liveWallpaperEnableAnywayButton": "Enable it anyway",
    "liveWallpaperHwAccelerationTooltip": "Enable it",
    "liveWallpaperHwAccelerationWarning": "Live Wallpaper is disabled due to lack of hardware acceleration",
    "liveWallpaperSetWindowsButton": "Set as Windows wallpaper",
    "liveWallpaperTitle": "Live Wallpaper",
    "liveWallpapersCompanionAppEnabled": false,
    "locationCountry": "US",
    "locationRegion": "unknown",
    "mondayApiDomain": "https://gx.opera-api2.com",
    "mondayDealsFeedbackBadge": "Feedback",
    "navRateOpera": "Rate Opera",
    "newMdExtensionsFlagSet": true,
    "newStickySiteFeaturesEnabled": false,
    "newsCDN": "",
    "newsOnStartpageHeaderChooseLanguageAndCountry": "Choose language and country",
    "ok_button": "OK",
    "open_items_button": "Open items",
    "open_many_confirmation": "Do you really want to open $1 items?",
    "openingAnimationEnabled": false,
    "os": {
        "PLATFORM_LINUX": "lin",
        "PLATFORM_MAC": "mac",
        "PLATFORM_WIN": "win",
        "VERSION_10": 7,
        "VERSION_7": 4,
        "VERSION_8": 5,
        "VERSION_XP": 1,
        "platform": "win",
        "version": 25
    },
    "pageTabTitle": "$1 - $2",
    "pinboard": true,
    "playAgain": true,
    "playAgainMenuDiscardAll": "Discard all items",
    "playAgainSectionName": "Play again on GX.games",
    "plusButtonTitle": "Add a site",
    "plusButtonTitleShort": "Add site",
    "privacyProtectionEnabled": true,
    "privateMode": false,
    "productName": "Opera GX",
    "rateOpera": "Rate Opera",
    "rateOperaCommentPlaceholder": "Comments",
    "rateOperaDialogAriaLabel": "Rate Opera dialog",
    "rateOperaEmailPlaceholder": "Email address",
    "rateOperaLabelAverage": "Average",
    "rateOperaLabelBad": "Bad",
    "rateOperaLabelClickToRate": "Click to rate",
    "rateOperaLabelExcellent": "Excellent",
    "rateOperaLabelGood": "Good",
    "rateOperaLabelTerrible": "Terrible",
    "rateOperaNoThanksButton": "No thanks",
    "rateOperaSubmitButton": "Submit",
    "reactinatorClose": "Close",
    "reactinatorMute": "Mute",
    "reactinatorNext": "Next track",
    "reactinatorPrev": "Previous track",
    "reactinatorRemove": "Remove",
    "reactinatorResize": "Resize",
    "reactinatorUnmute": "Unmute",
    "reactinatorUpload": "Import",
    "recordSessionEventStatsForTesting": false,
    "relaunch": "Relaunch",
    "richWallpapers": true,
    "runAtStartupEnabled": true,
    "search": "Search",
    "searchButton": "Search",
    "searchPageHelpText": "Maybe try using a different search query?",
    "searchPageNoMatches": "Nothing found for \"$1\"",
    "searchPageTitle": "Search results",
    "searchTheWeb": "Search the web",
    "shoppingCorner": false,
    "sideProfilesEnabled": true,
    "startPageContentEnabled": false,
    "startPageSyncBanner": false,
    "storiesHideRecommendedStories": "Hide Content Picks",
    "storiesInfoLearnMore": "Learn more",
    "storiesInfoTooltip": "A new format of useful content from top trusted sources curated by Opera.",
    "storiesRecommendedStories": "Content Picks",
    "suggestionsHeader": "Suggestions",
    "syncBannerButton": "Turn on synchronization",
    "syncBannerDesc": "Sync your bookmarks, tabs, passwords to back them up and access on connected devices",
    "syncBannerEnabled": false,
    "syncBannerLater": "Later",
    "syncBannerTitle": "Back up your Opera browser",
    "systemThemeFeatureEnabled": true,
    "textdirection": "ltr",
    "themeDarkLabel": "Dark",
    "themeEnv": "",
    "themeLightLabel": "Light",
    "themeSystemLabel": "System",
    "themeTitle": "Theme",
    "transparentProductPages": true,
    "urlHost": "startpage",
    "vpnPro": true,
    "wallpaperTakeover": true,
    "wallpapersAddNew": "Add your wallpaper",
    "wallpapersGetMore": "Get more wallpapers",
    "wallpapersSiteURL": "https://addons.opera.com/wallpapers/?gx&ref=page",
    "weatherChangeLocation": "Change location",
    "weatherCheckForecast": "Check forecast",
    "weatherDetectLocation": "Detect current location",
    "weatherForecastNotAvailable": "Weather forecast not available.",
    "weatherModalAgree": "Agree",
    "weatherModalCancel": "Cancel",
    "weatherModalChangeYourLocation": "Change your location",
    "weatherModalGeolocationServicesExplanation": "To get a correct weather forecast, the browser will send a request to Google Location Services to determine your location and forward it to Opera.",
    "weatherModalPrivacyInfo": "Opera servers do not store or share your location with any third party, including the provider of the weather forecast.",
    "weatherModalPrivacyPolicy": "Privacy policy",
    "weatherModalSave": "Save",
    "weatherModalSetLocationManually": "Set location manually",
    "weatherModalTitle": "Weather Location",
    "weatherOnBoardingTooltip": "Set up your city",
    "webuiDebugModeEnabled": false,
    "webuiHost": "op-resources",
    "webuiScheme": "chrome",
    "wpTakeoverPromptHeader": "Do you wanna keep it?",
    "wpTakeoverPromptNo": "No, thanks :(",
    "wpTakeoverPromptYes": "Yes, keep it!",
    "wpTakeoverPromptYesForToday": "Yes, keep it for today!",
    "zenNewsLoadErrorSimulate": false
};
